#name of the workflow
name: Build & Deploy
#trigger point. For triggering jobs on main branch when push event happens.
#we could include multiple branches.
on:
  push:
    branches:
      - main

#ignore warnings. If set true, then for any workflow the buid will stop.
#in production should be set trure
env:
  CI: false
#jobse, we have build and deploy
jobs:
  #define steps for build jobs
  build:
    name: Build and Test
    #we need to pick a server in github to run the job
    runs-on: ubuntu-latest
    #define the steps for build job
    steps:
    - name: Chekcout repo
      uses: actions/checkout@v4
    - name: Set up Python 3.10.14
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.14"
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      run: |
        pytest tests/load_data_test.py
        pytest tests/preprocessing_test.py
    

